[build]
  command = "yarn build"
  publish = "public/"
[build.environment]
  NETLIFY_USE_YARN = "true"
[build.processing.html]
  pretty_urls = true

[template]
  incoming-hooks = ["Webflow"]

[template.environment]
  WEBFLOW_URL = "well-made.uk"
[template.environment]
  TARGET = "https://639f83e12c118d541d47f921--funny-eclair-07cf0b.netlify.app/"

[[plugins]]
package = "netlify-plugin-subfont"

[[plugins]]
package = "netlify-plugin-image-optim"

[build.processing]
  skip_processing = false
[build.processing.css]
  bundle = true
  minify = true
[build.processing.js]
  bundle = true
  minify = true
[build.processing.images]
  compress = true
